"""position-positionSplit link added

Revision ID: 047e92892876
Revises: c6cf6b6f6a1f
Create Date: 2019-06-20 17:58:40.103281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047e92892876'
down_revision = 'c6cf6b6f6a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positionsplit', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'positionsplit', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positionsplit', type_='foreignkey')
    op.drop_column('positionsplit', 'position_id')
    # ### end Alembic commands ###
