"""p_mc and p_md added to Position

Revision ID: 10036e1d81b0
Revises: 22d218f6adf2
Create Date: 2019-06-18 16:30:26.718613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10036e1d81b0'
down_revision = '22d218f6adf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('p_mc', sa.Float(), nullable=True))
    op.add_column('position', sa.Column('p_md', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'p_md')
    op.drop_column('position', 'p_mc')
    # ### end Alembic commands ###
