"""newparams added to Session

Revision ID: 160fb057f4e5
Revises: 1a350db99355
Create Date: 2020-02-12 17:16:42.378233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160fb057f4e5'
down_revision = '1a350db99355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('newparams', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'newparams')
    # ### end Alembic commands ###
