"""link between strategy and session added

Revision ID: 16c23bb17454
Revises: 920924b076b5
Create Date: 2019-06-18 11:42:29.743755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c23bb17454'
down_revision = '920924b076b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessionstratetgy',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionstratetgy')
    # ### end Alembic commands ###
