"""Extension model added to db

Revision ID: 2284dd177349
Revises: 10036e1d81b0
Create Date: 2019-06-18 17:44:04.142742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2284dd177349'
down_revision = '10036e1d81b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.String(length=20), nullable=True),
    sa.Column('tickscounter', sa.Integer(), nullable=True),
    sa.Column('p_mc', sa.Float(), nullable=True),
    sa.Column('p_md', sa.Float(), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('strategyname', sa.String(length=64), nullable=True),
    sa.Column('groi', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extension')
    # ### end Alembic commands ###
