"""file column with evolution added to Position

Revision ID: 22d218f6adf2
Revises: 16c23bb17454
Create Date: 2019-06-18 14:06:06.680447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d218f6adf2'
down_revision = '16c23bb17454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('filecontent', sa.LargeBinary(), nullable=True))
    op.add_column('position', sa.Column('filename', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'filename')
    op.drop_column('position', 'filecontent')
    # ### end Alembic commands ###
