"""strategyidx added to Position

Revision ID: 2c9f80fe65fc
Revises: 63ef97eb1cee
Create Date: 2020-04-21 10:24:50.332582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9f80fe65fc'
down_revision = '63ef97eb1cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('strategyidx', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'strategyidx')
    # ### end Alembic commands ###
