"""session-position link added

Revision ID: 4093663b34e0
Revises: c84f3ab06276
Create Date: 2019-06-20 17:54:55.618646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4093663b34e0'
down_revision = 'c84f3ab06276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'position', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'position', type_='foreignkey')
    op.drop_column('position', 'session_id')
    # ### end Alembic commands ###
