"""Deposit table added

Revision ID: 5d327b8a1c2b
Revises: cd7d3234b8f5
Create Date: 2020-02-19 10:39:39.218901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d327b8a1c2b'
down_revision = 'cd7d3234b8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposit')
    # ### end Alembic commands ###
