"""account status added to Trader

Revision ID: 63ef97eb1cee
Revises: 883ea4369578
Create Date: 2020-03-17 16:40:40.586860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ef97eb1cee'
down_revision = '883ea4369578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trader', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('trader', sa.Column('equity', sa.Float(), nullable=True))
    op.add_column('trader', sa.Column('leverage', sa.Float(), nullable=True))
    op.add_column('trader', sa.Column('profits', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trader', 'profits')
    op.drop_column('trader', 'leverage')
    op.drop_column('trader', 'equity')
    op.drop_column('trader', 'balance')
    # ### end Alembic commands ###
