"""user tokens

Revision ID: 920924b076b5
Revises: 02c0a47e4ceb
Create Date: 2019-06-11 17:11:16.334422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920924b076b5'
down_revision = '02c0a47e4ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
