"""swap added to Position

Revision ID: 957d4371eafe
Revises: 5d327b8a1c2b
Create Date: 2020-02-21 13:57:45.766607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957d4371eafe'
down_revision = '5d327b8a1c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('swap', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'swap')
    # ### end Alembic commands ###
