"""trader-asset link added

Revision ID: 9e02fe66741e
Revises: 76affcf8b224
Create Date: 2019-06-20 17:48:17.434670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e02fe66741e'
down_revision = '76affcf8b224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traderasset',
    sa.Column('trader_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.assetname'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['trader.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traderasset')
    # ### end Alembic commands ###
