"""deposit added to User

Revision ID: cc4f40f73a38
Revises: 160fb057f4e5
Create Date: 2020-02-17 10:56:10.985876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4f40f73a38'
down_revision = '160fb057f4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deposit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deposit')
    # ### end Alembic commands ###
