"""sessiontest added to Session

Revision ID: cd7d3234b8f5
Revises: cc4f40f73a38
Create Date: 2020-02-18 11:37:41.209781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7d3234b8f5'
down_revision = 'cc4f40f73a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('sessiontest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'sessiontest')
    # ### end Alembic commands ###
