"""session added

Revision ID: cf2bac4e4b23
Revises: 9e02fe66741e
Create Date: 2019-06-20 17:51:35.519498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2bac4e4b23'
down_revision = '9e02fe66741e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('sessionname', sa.String(length=64), nullable=True),
    sa.Column('sessiontype', sa.String(length=10), nullable=True),
    sa.Column('dti', sa.DateTime(), nullable=True),
    sa.Column('dto', sa.DateTime(), nullable=True),
    sa.Column('groisoll', sa.Float(), nullable=True),
    sa.Column('groiist', sa.Float(), nullable=True),
    sa.Column('roisoll', sa.Float(), nullable=True),
    sa.Column('roiist', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.Column('meanspread', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_sessionname'), 'session', ['sessionname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_sessionname'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
